# # Remap prefix to C-a
# unbind C-b
# set -g prefix C-Space
# bind-key -n C-, send-prefix

# Have vim keybindings
set-window-option -g mode-keys vi

# Start window numbering from 1
set -g base-index 1

# Set the window switching to vim keybindings
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Open new window in same directory
bind-key c new-window  -c "#{pane_current_path}"
set-window-option -g allow-rename off

# Enable Mouse
set -g mouse on

set -sg escape-time 0

# Set terminal with proper colors
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"
